# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '10_RunTime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 10_RunTime
#Objective-c
pod 'YYModel'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'XMLReader-PPTV'
  pod 'WebViewJavascriptBridge'
  pod 'SocketRocket'
  pod 'Masonry'


end
